# Unidad 3: Estructuras de Datos - Matrices

### Vectores y Matrices con numpy

Características de numpy

- numpy es una biblioteca fundamental para el cálculo numérico en Python.

- Permite manejar datos numéricos en arreglos multidimensionales (vectores, matrices y tensores).

- Ofrece operaciones matemáticas rápidas y eficientes gracias a su implementación en C y Fortran.

- Ideal para análisis de datos, inteligencia artificial y procesamiento de señales.

In [1]:
# Importar la biblioteca
import numpy as np

In [2]:
# Crear vectores
vector_a = np.array([1, 2, 3])  # Vector fila
vector_b = np.array([[1], [2], [3]])  # Vector columna

In [3]:
print(vector_a)  # [1 2 3]
print(vector_b)  # [[1] [2] [3]]

[1 2 3]
[[1]
 [2]
 [3]]


In [4]:
# Crear matrices
matriz_2x2 = np.array([[1, 2], [3, 4]])
matriz_3x3 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz_2x3 = np.array([[1, 2, 3], [7, 8, 9]])


In [6]:
print(matriz_2x2)

[[1 2]
 [3 4]]


In [7]:
print(matriz_3x3)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
print(matriz_2x3)

In [9]:
# Matrices con ceros y unos
ceros = np.zeros((3, 3))
unos = np.ones((2, 4))
identidad = np.eye(4)  # Matriz identidad 4x4

print(ceros)
print(unos)
print(identidad)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


### Indexación y Slicing Avanzado

In [10]:
# Matriz de ejemplo
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Acceder a un elemento
print(matriz[0, 0])  # 1
print(matriz[2, 1])  # 8

# Slicing de filas y columnas
print(matriz[1, :])  # [4 5 6]
print(matriz[:, 1])  # [2 5 8]
print(matriz[0:2, 0:2])  # Submatriz 2x2

# Filtrado de elementos
print(matriz[matriz > 4])  # [5 6 7 8 9]

1
8
[4 5 6]
[2 5 8]
[[1 2]
 [4 5]]
[5 6 7 8 9]


In [12]:
# Operaciones entre vectores y matrices
vector_1 = np.array([1, 2, 3])
vector_2 = np.array([4, 5, 6])

# Suma y resta
suma = vector_1 + vector_2
resta = vector_1 - vector_2
print(suma)  # [5 7 9]
print(resta)  # [-3 -3 -3]

[5 7 9]
[-3 -3 -3]


In [ ]:
# Producto por escalar
escalar = 3 * vector_1
print(escalar)  # [3 6 9]

In [13]:
# Producto punto
producto_punto = np.dot(vector_1, vector_2)
print(producto_punto)  # 32

32


In [14]:
# Producto de matrices
matriz_a = np.array([[1, 2], [3, 4]])
matriz_b = np.array([[2, 0], [1, 2]])

In [ ]:
producto_matrices = np.dot(matriz_a, matriz_b)
print(producto_matrices)
# [[4 4]
#  [10 8]]

# Transposición de matrices
print(matriz_a.T)
# [[1 3]
#  [2 4]]

# Determinante y traza
print(np.linalg.det(matriz_a))  # -2.0
print(np.trace(matriz_a))  # 5

### Ejercicios para Practicar

Crear un vector de 10 elementos y:

- Calcular la suma y el promedio de todos los elementos.

- Obtener los elementos mayores a 5.

- Multiplicar cada elemento por 2 y mostrar el resultado.

Crear una matriz 3x3 y:

- Calcular la suma de cada fila y cada columna.

- Obtener la matriz transpuesta.

- Calcular su determinante.

Crear dos matrices de 2x2 y:

- Calcular su producto (matricial y elemento a elemento).

- Verificar si son iguales tras la transposición.

Crear una matriz 4x4 con números aleatorios entre 0 y 100 y:

- Obtener solo los elementos mayores a 50.

- Reemplazar los elementos menores a 30 por 0.

- Calcular la suma de la diagonal principal.

Crear un vector de 100 elementos con valores aleatorios y:

- Encontrar el máximo, mínimo y su posición.

- Calcular la desviación estándar.

- Ordenar los elementos en orden ascendente y descendente.

Crear una matriz identidad de 5x5 y:

- Multiplicarla por un escalar de tu elección.

- Sumarle otra matriz de 5x5 con valores aleatorios.

- Verificar si sigue siendo una matriz identidad después de estas operaciones.